### ISSUE TITLE
求问！总保研人数62，最后一名排名86，这里的排名是绩点排名还是综合排名呢？

### ISSUE THREAD

**Issue by Ultrasty** [NJU-SE-15-share-review/postgraduate-recommendation#22]
——来自一位什么都不懂的学弟

**Comment by Ultrasty** [comment]
会有多少比例的有保研资格的同学放弃保研选择出国或工作呢![QQ图片20210501230522](https://user-images.githubusercontent.com/51046846/116786524-b8306c00-aad1-11eb-85fd-9681278a6b4c.png)

**Comment by ddadaal** [comment]
有个专门的推免的综合排名，大概是所有的必修课+大三选的算学分得分课（16级的前两年的课基本都是一样的吧，只有大三会让选自己的方向，每个方向自己的算学分的课，不知道之后是怎样的），在快决定保研名单的时候会出

有多少同学放弃保研可以从人数和排名算出来吧？一般来说能保研的选择考研的比较少（但是有），这两个数字的差值基本就是可以保研但是放弃，去出国或工作的人数了。

**Comment by Ultrasty** [comment]
@ddadaal 嗯嗯！ 谢谢你！
放弃保研有24个人感觉有点多，打破了我的固有看法![](https://user-images.githubusercontent.com/51046846/116870949-0e262080-ac46-11eb-8c8f-0a9ffa84eafa.png)

![微信图片_20210503193421](https://user-images.githubusercontent.com/51046846/116871271-97d5ee00-ac46-11eb-947d-8884568f81e9.png)
因为之前注意到这里的表述，我一直以为86是某位同学的GPA排名，因为有科研或竞赛加分才保上研的![](https://user-images.githubusercontent.com/51046846/116871515-f602d100-ac46-11eb-9986-859545d5972f.png)
